name: Security Scan and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Save commit SHA
        id: get_sha
        run: echo "sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  trufflehog_scan:
    name: Run TruffleHog Scan
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run TruffleHog
        run: |
          docker run --rm -v ${{ github.workspace }}:/src trufflesecurity/trufflehog:latest \
            filesystem /src --exclude-paths /src/trufflehog-excluded-paths.txt --fail --json \
            | tee trufflehog-scan-result.json

          if [ "$(jq 'length' trufflehog-scan-result.json)" -gt 0 ]; then
            echo "❌ TruffleHog found secrets!"
            exit 1
          fi
        continue-on-error: true

      - name: Archive TruffleHog Result
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-scan-result.json

  setup_node:
    name: Setup Node.js & Install Dependencies
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

  docker_build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [setup_node, trufflehog_scan]
    env:
      DEPLOY_USERNAME: ubuntu
      DEPLOYMENT_IP: 192.168.1.11
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t xenjutsu/nodejsgoof:latest .

      - name: Push Docker Image
        run: docker push xenjutsu/nodejsgoof:latest
