retirejs_scan:
    name: Retire.js Scan
    runs-on: ubuntu-latest
    needs: setup_node
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Retire.js
        run: npm install retire

      - name: Run Retire.js
        id: retirejs
        run: |
          ./node_modules/retire/lib/cli.js --outputformat json --outputpath retire-scan-report.json || true
          if [ "$(jq '.data | length' retire-scan-report.json)" -gt 0 ]; then
            echo "found_vulns=true" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "found_vulns=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Show Retire.js Report
        run: cat retire-scan-report.json

      - name: Upload Retire.js Report
        uses: actions/upload-artifact@v4
        with:
          name: retire-scan-report
          path: retire-scan-report.json

      - name: Set GitHub Status for Retire.js Scan
        if: always()
        run: |
          if [ "${{ steps.retirejs.outputs.found_vulns }}" = "true" ]; then
            state="failure"
            description="Retire.js found vulnerabilities!"
          else
            state="success"
            description="Retire.js scan passed"
          fi

          json=$(printf '{"state":"%s","context":"retirejs-scan","description":"%s"}' "$state" "$description")

          curl -s -X POST \
            -H "Authorization: token ${{ secrets.STATUS_CHECK_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d "$json"


  trivy_dockerfile_scan:
    name: Trivy Dockerfile Scan
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Config Scan
        id: trivy
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            aquasec/trivy:latest config /project/Dockerfile --format json --exit-code 1 > trivy-scan-dockerfile-report.json || true

          failures=$(jq '[.Results[].MisconfSummary.Failures] | add' trivy-scan-dockerfile-report.json)
          echo "failures=$failures" >> $GITHUB_OUTPUT

      - name: Show Trivy Dockerfile Report
        run: cat trivy-scan-dockerfile-report.json

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-dockerfile-report
          path: trivy-scan-dockerfile-report.json

      - name: Set GitHub Status for Trivy Dockerfile Scan
        if: always()
        run: |
          if [ "${{ steps.trivy.outputs.failures }}" -gt 0 ]; then
            state="failure"
            description="Trivy found Dockerfile misconfigurations!"
          else
            state="success"
            description="Trivy Dockerfile scan passed"
          fi

          json=$(printf '{"state":"%s","context":"trivy-dockerfile-scan","description":"%s"}' "$state" "$description")

          curl -s -X POST \
            -H "Authorization: token ${{ secrets.STATUS_CHECK_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d "$json"